# .github/workflows/java-build-deploy.yml
name: Java Build & Deployment Example - DoX-CLI Action

on:
  workflow_call:
    inputs:
      jdk_version:
        description: 'JDK Version'
        type: string
        default: '17'
      debug_mode:
        description: 'Enable Debug Mode'
        type: string
        default: 'true'    
      oci_reg_host:
        description: 'OCI Registry Username'
        type: string
        default: 'docker.io'    
      oci_reg_user:
        description: 'OCI Registry Username'
        type: string
        required: true
      docker_image_push_prefix:
        description: 'Docker Image Push Prefix'
        type: string
        required: true
      gitops_repository:
        description: 'GitOps Repository '
        type: string
        default: 'github.com/dopxlab/gitops-argocd.git'    
      app_configmap:
        description: 'Config map ref in deploment'
        type: string
        default: ''    
      app_secret:
        description: 'Secret  ref in deploment'
        type: string
        default: ''    
      app_pvc:
        description: 'PVC binding with deploment'
        type: string
        default: ''            
    secrets:
      oci_reg_password:
        description: 'OCI Registry Password'
        required: true
      gitops_pat:
        description: 'Personal Access Token for Github'
        required: true

jobs:
  cicd:
    runs-on: ubuntu-latest
    env:
      JDK_VERSION: ${{ inputs.jdk_version }}
      DEBUG_MODE: ${{ inputs.debug_mode }}
      DOCKER_IMAGE_PUSH_PREFIX: ${{ inputs.docker_image_push_prefix }}
      OCI_REG_HOST: ${{ inputs.oci_reg_host }}
      OCI_REG_USER: ${{ inputs.oci_reg_user }}
      GITOPS_REPO: ${{ inputs.gitops_repository }}
      APP_CONFIGMAP: ${{ inputs.app_configmap }}
      APP_SECRET: ${{ inputs.app_secret }}
      APP_PVC: ${{ inputs.app_pvc }}

      GITOPS_PAT: ${{ secrets.gitops_pat }}
      OCI_REG_PASSWORD: ${{ secrets.oci_reg_password }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Install DOX CLI
        run: |
          curl -s -L -o install.sh https://github.com/dopxlab/dox-cli/releases/latest/download/install.sh && bash install.sh
          cp $HOME/.dox/bin/* /usr/local/bin/

      - name: Maven Build
        run: |
          dox configure maven
          mvn clean install

      - name: Docker Build & Push
        run: |
          dox docker build push

      - name: GitOps Deploy
        run: |
          dox gitops update-image-tag
